seq2seq:
  embedding_dim: 256
  hidden_dim: 1000
  num_layers: 3
  dropout:
    encoder: 0.5
    decoder: 0.2
  activation: Softmax
transformer:
  embedding_dim: 96
  forward_dim: 1000
  num_layers: 6
  num_heads: 3
  dropout:
    encoder: 0.1
    decoder: 0.1
  activation: Softmax