train:
  batch_size: 64
  epochs: 100
  optimizer: RMSprop
test:
  input_file: './res/test_input.txt'
  result_file: './res/test_result.txt'
  validation_split: 0.2
max_checkpoints: 10
model_dir: './res/weights'