train_file: './res/dataset.txt'
test_file:
  input: './res/test_input.txt'
  result: './res/test_result.txt'
size: 5000
vocab_size: 2000
filters: "!$&*+,-./;<=>?#[\\]^_`{|}~\t\n"
hours:
  - ''
  - '00:00'
  - '01:00'
  - '02:00'
  - '03:00'
  - '04:00'
  - '05:00'
  - '06:00'
  - '07:00'
  - '08:00'
  - '09:00'
  - '10:00'
  - '11:00'
  - '12:00'
  - '13:00'
  - '14:00'
  - '15:00'
  - '16:00'
  - '17:00'
  - '18:00'
  - '19:00'
  - '20:00'
  - '21:00'
  - '22:00'
  - '23:00'
targets:
  - ''
  - 'att'
  - 'bell'
  - 'ufrgs'
  - 'pucrs'
  - 'company'
  - 'adp'
  - 'example'
middle_boxes:
  - 'firewall'
  - 'dpi'
  - 'ids'
  - 'load-balancer'
  - 'parental-control'
usernames:
  - 'asjacobs'
  - 'granville'
  - 'rjpfitscher'
  - 'ronaldo'
locations:
  - ''
  - 'database'
  - 'marketing'
  - 'gateway'
  - 'backend'
  - 'ps4'
  - 'asjacobs-pc'
traffic:
  - ''
  - 'udp'
  - 'http'
  - 'netflix'
  - 'youtube'
qos_metrics:
  -
    - 'latency'
    - 'ms'
  -
    - 'loss'
    - '%'
  -
    - 'jitter'
    - 'ms'
  -
    - 'bandwidth'
    - 'mbps'
qos_constraints:
  - 'less'
  - 'more'
  - 'equal'
  - 'none'