seq2seq:
  embedding_dim: 256
  hidden_dim: 1000
  num_layers: 3
  dropout:
    encoder: 0.5
    decoder: 0.2
  teacher_forcing_ratio: 0.5

transformer:
  embedding_dim: 512
  forward_dim: 2048
  num_layers: 6
  num_heads: 8
  dropout:
    encoder: 0.1
    decoder: 0.1
  activation: Softmax