train:
  device: cuda
  model: transformer
  optimizer: RMSprop
  loss: CrossEntropyLoss
  batch_size: 64
  epochs: 100
  lr:
    initial: 1e-4
    scheduler: null
  saving_every_epochs: 10
  max_saving_checkpoints: 10

test:
  input_file: './res/test_input.txt'
  result_file: './res/test_result.txt'
  validation_split: 0.2

checkpoint_dir: './res/weight/'