train:
  optimizer: RMSprop
  loss: CrossEntropyLoss
  batch_size: 64
  epochs: 2000
  lr: 1.0e-4
  saving_interval_epochs: 10
  log_interval_steps: 10
  max_saving_checkpoints: 10

test:
  input_file: './res/test_input.txt'
  result_file: './res/test_result.txt'
  validation_split: 0.2

model: transformer
device: cuda
checkpoint_dir: './res/weights/'